### ISSUE TITLE
RunnerCukes stalls out v. 93e1a9d1f9

### ISSUE THREAD

**Issue by DanielSaganome** [saikrishna321/AppiumTestDistribution#123] opened 2016-10-19 14:27 UTC
Hey man awesome project you got here, really useful. 

I'm trying to run the cucumber tests from your PageObjectPatternAppium project, with the latest commit of this project (93e1a9d1f9) but when it starts the tests, it reads the feature file, prints the feature description and then stalls indefinitely.

Running project through command line
mvn clean -Dtest=RunnerCukes test

This is the line where it stalls out
***************_Device**_**********As a user i should be able to Add comments

I followed the configurations you laid out for cucumber.
FRAMEWORK=cucumber
<useTestNG>false</useTestNG> 

Looking at other issues I noticed that last commit where this issue doesn't occur is with the commit (2dcc0b9476). The reason I don't revert back to that commit is because it's before the bug fix where tests would run on the wrong OS. 

Appreciate the help, thanks.

**Comment by saikrishna321** [comment] 2016-10-19 15:53
@DanielSaganome Thanks a lot for trying out the repo, pls user v 5.0.1 for cucumber, the master is broken on cucumber runner. 

The issue is fast and hard rule, still needs to be fixed. Will look into it ASAP, stuck with project work. 

Give it a try with v5.0.1 and ping back if any help is needed

**Comment by DanielSaganome** [comment] 2016-11-07 17:02
Hey so I decided to fork to the project and play around and I got cucumber running using your latest commit (a12b29d9d3). 

I narrowed the problem down to only a couple lines of code in AppiumParallelTest.java in startAppiumServer(String device) method. Basically the issue is that the device UDID was being set to the parameter of this method but this method is called by feature() in ExtentCucumberFormatter.java which passes the feature name as the parameter so the device UDID was being set to the feature name.

I've tested the changes on real devices, iOS and Android in parallel and separately and it seems to work fine. 

I attached the code comparison pic here. Let me know your thoughts, thanks.

![screen shot 2016-11-07 at 11 47 35 am](https://cloud.githubusercontent.com/assets/22822788/20067159/08b9bd7a-a4e2-11e6-9b2c-e9cde50324a3.png)

**Comment by SrinivasanTarget** [comment] 2016-11-07 17:35
@DanielSaganome Awesome 👍 We will review this soon. Thanks for your work.

**Comment by DanielSaganome** [comment] 2016-11-07 18:38
Sure, would you guys like me to make a pull request?

**Comment by saikrishna321** [comment] 2016-11-08 04:14
@DanielSaganome initially this was the implementation, which had the bug. When tests are completed on device3 and device2 is still running and has pending one testcase, then the getNextAvailableDevices() checks and pulls the pending test-cases, so when running in parallel we need to allocate the device UDID to set of test cases...

**Comment by saikrishna321** [comment] 2016-11-08 04:14
Myself and @SrinivasanTarget are looking into it.. @DanielSaganome if you have any ideas pls chip in

**Comment by saikrishna321** [comment] 2016-11-23 14:44
@DanielSaganome its fixed in the below version. Pls give it a try and update 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version> 5d1ed9602e </version>
	</dependency>
```

**Comment by DanielSaganome** [comment] 2016-12-05 15:31
@saikrishna321 That's awesome, Im trying it out right now but when I try to run cucumber it defaults to the TestNG runner for some reason. Running the command mvn clean -Dtest=RunnerCukes test. Besides the dependency change, nothing else in my project has changed so I don't think its on my end. I'm looking into it right now, just thought I'd let you know. Again awesome work 👍

**Comment by saikrishna321** [comment] 2016-12-05 15:36
pls check the config.properties if the FRAMEWORK=cucumber

**Comment by DanielSaganome** [comment] 2016-12-05 15:45
Found the issue, looks like it was in my pom file. I had <useTestNG>false</useTestNG> but ironically it works when it's set to true. Testing it now

**Comment by saikrishna321** [comment] 2016-12-05 16:17
@DanielSaganome awesome ... waiting to hear back

**Comment by DanielSaganome** [comment] 2016-12-05 16:33
Everything looks good! Thanks man appreciate it 👍

**Comment by saikrishna321** [comment] 2016-12-05 16:33
@DanielSaganome Great :) Glad it worked :) I'm happy this library is helping

**Closed by saikrishna321** 2016-12-05 16:33 UTC
