### ISSUE TITLE
Test executed on wrong device in parallel Android + iOS setup

### ISSUE THREAD

**Issue by brtu** [saikrishna321/AppiumTestDistribution#90] opened 2016-07-26 18:50 UTC
I have 3 tests that I am running in parallel on an Android and iOS tablet.  Test1 and Test2 get run on both Android and iOS devices.  However, Test3 runs twice on the Android device and zero times on the iOS device.

My Android test takes around 1 minute, while the iOS test (same test) takes 1.5-2 minutes.  What happens is that the Android device finishes all 3 of its tests, while the iOS device is still on Test2.  Instead of Test3 being scheduled to run on the iOS device and getting put in a queue, it instead runs on the Android device.

**Comment by saikrishna321** [comment] 2016-07-28 10:02
@brtu does this happen consistently ?

**Comment by brtu** [comment] 2016-07-29 19:10
Yes, it is consistent behavior.  I think I've narrowed it down more - whenever the iOS device is unavailable, then the test that was supposed to run on it gets sent to the Android device instead.

I had 3 tests set to run in parallel on both Android and iOS.  The iPad had a software update popup which prevented Instruments from launching.  The first iOS test did not run and was skipped.  Then five tests (Test1, Test2, and Test3 meant for Android as well as Test2 and Test3 meant for iOS) ran on the Android device.

So it looks like when a device is "unavailable", the distribution mode is activated and the tests get distributed to any available devices instead and doesn't respect the device's OS.

**Comment by brtu** [comment] 2016-08-02 19:07
Just saw his happen while running tests on 2 Android devices.  Looks like a problem with running tests in parallel.  If one device finishes a set of tests first, then it gets more tests scheduled to it.

**Comment by brtu** [comment] 2016-08-02 20:10
Definitely looks like a problem with using Cucumber in AppiumTestDistribution.  In the MyTestExecuter file and parallelTests method, there is no logic that specifies how the tests are split between the different devices.

**Comment by saikrishna321** [comment] 2016-08-02 23:49
So your tests in parallel or distributed mode ? Can u reproduce this with sample project provided.

**Comment by brtu** [comment] 2016-08-03 00:03
The tests are in parallel mode.  I spent some time looking through the source code today.  I think the problem might be here:

https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L123

At this line, the thread just gets the next available deviceId that is free instead of a dedicated deviceId.  I think this allows tests to be run on the wrong device.

**Comment by saikrishna321** [comment] 2016-08-03 08:23
@brtu i'm unable to reproduce this.

For ex: Test1,Test2,Test3 -- 2 android devices -- i see all three tests cases are running on both the devices..

**Comment by brtu** [comment] 2016-08-03 21:56
@saikrishna321 

I forked and modified the PageObjectAppium project to demonstrate the bug.

Fork: https://github.com/brtu/PageObjectPatternAppium

Changes: https://github.com/saikrishna321/PageObjectPatternAppium/compare/master...brtu:master

I had to change the AppiumTestDistribution dependency because the current one included in the project doesn't work with 5.0.1 release, so I forked AppiumTestDistribution and released a version with the latest commits.  I also stripped the Cucumber feature and step files to the bare bones because some Appium commands in the step files are not working with Appium 1.5.3.

I have 2 Android devices, with udids R32CA054KZH and HT52SJT00021.  When I set all tests on HT52SJT00021 to take an extra minute, then Test1, Test2, and Test3 run on both HT52SJT00021 and R32CA054KZH.  However, when I set all tests on R32CA054KZH to take an extra minute, then Test1 runs on R32CA054KZH, and Test1, Test2, Test3, Test1, and Test2 run on HT52SJT00021.

Seems like the order of the devices matter in determining how the tests are distributed to the devices in parallel.  With one order it works correctly, but if you switch the order then the bug happens.

**Comment by saikrishna321** [comment] 2016-08-04 04:35
@brtu thanks a lot for sample tests... will take a look this weekend, bit busy with project work.

If its reproducible in cucumber then it should b on TestNG as well..

**Comment by saikrishna321** [comment] 2016-08-04 13:08
@brtu i could reproduce.. Thanks for reporting 👍

**Comment by brtu** [comment] 2016-08-04 14:42
@saikrishna321 Great to hear that you could reproduce it!!  I am trying to fix the bug as well but am still unfamiliar with a lot of the AppiumTestDistribution project.  Thank you for your work on building AppiumTestDistribution, it is really a great project and I am happy to contribute to it.

**Comment by saikrishna321** [comment] 2016-08-28 09:52
@brtu were u able to fix the issue ? if not i will start working on it

**Comment by brtu** [comment] 2016-08-28 13:34
@saikrishna321 No, I wasn't able to fix the issue.  Got sidetracked and was working on other stuff.  Yes, it would be great if you can fix it!

**Comment by saikrishna321** [comment] 2016-08-28 17:04
@brtu your runner is testNG or cucumber ?

**Comment by brtu** [comment] 2016-08-28 17:34
Cucumber

**Comment by saikrishna321** [comment] 2016-09-11 03:49
@brtu i have made fixes for testNG runner, will do it for cucumber next ..

**Comment by Balhindi** [comment] 2016-11-07 19:24
Sai, any update on this sir? I also run into the same problem. Thank you so much for all of your work

**Comment by saikrishna321** [comment] 2016-11-23 14:45
@brtu @Balhindi its fixed now, try the below version 
```
<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version> 5d1ed9602e </version>
</dependency>
```

**Comment by Balhindi** [comment] 2016-12-06 18:40
I have tried to run the project with the instructions you have given (It worked before in previous versions), but with the newest snapshot I can't run any cucumber project. I left a runner in the test folder. Have any ideas?

**Comment by brtu** [comment] 2016-12-06 20:59
@saikrishna321 Thanks Sai!

@Balhindi Try setting <useTestNG>true</useTestNG> in the pom.xml

**Comment by saikrishna321** [comment] 2016-12-07 04:30
@brtu can you pls raise a new defect for this will look into it ..

**Closed** 2016-12-07 16:01 UTC
Labels: bug
